/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamestore;

import static gamestore.GamerPage.username;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Shadman
 */
public class CollectionPanel extends javax.swing.JPanel {
    
    int gameId;
    int gamerId;
    /**
     * Creates new form CollectionPanel
     */
    public CollectionPanel(JLabel imageLabel,String gameName, int rating, int gamerId, JFrame previousFrame) {
        initComponents();
        setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        this.gamerId = gamerId;
    
        this.add(imageLabel);
            try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=gamestoredb;integratedSecurity=true");  
            Statement statement = connection.createStatement();
            
            ResultSet rs = statement.executeQuery("select GameId from Game where Name='"+gameName+"'");
            rs.next();
            gameId = rs.getInt("GameId");
    
           } catch (Exception e) {}  
        
             BufferedImage bufferedImage = null;
            try {
                 bufferedImage = ImageIO.read(new File("src\\images\\"+rating+".png"));
            } catch (IOException ex){
                 Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        Image scaledImage = (Image) bufferedImage.getScaledInstance(60, 16, Image.SCALE_SMOOTH);
    
        JLabel ratingLabel = new JLabel(new ImageIcon(scaledImage));
        add(ratingLabel);
        
        JButton button = new JButton();
        button.setText(gameName);
        button.setPreferredSize(new Dimension(20, 16));
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });
        add(button);
        JButton reviewButton = new JButton("Review");
        reviewButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new WriteReview(gamerId, gameId, previousFrame).setVisible(true);
            }
        });
        add(reviewButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
