/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamestore;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Shadman
 */
public class ProductPanel extends javax.swing.JPanel {
    
    String gameName;
    int Rating;
    /**
     * Creates new form ProductPanel
     */
    public ProductPanel(JLabel imageLabel,String buttonText, String price, int rating, JFrame previousFrame, int gamerId) {
        initComponents(); 
        
        this.    
        setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        this.add(imageLabel);
        
        JButton button = new JButton();
        button.setText(buttonText);
        button.setPreferredSize(new Dimension(20, 16));
        
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              try{  
               new GameView(buttonText, (GamerPage)previousFrame, gamerId).setVisible(true);
              }
              catch(Exception ep){
               new GameViewAdmin(buttonText, (AdminPage)previousFrame).setVisible(true);
              }
            }
        });
        this.add(button);

        //ratingLabel.setPreferredSize(new Dimension(20, 16));
        
        BufferedImage bufferedImage = null;
            try {
                 bufferedImage = ImageIO.read(new File("src\\images\\"+rating+".png"));
            } catch (IOException ex){
                 Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        Image scaledImage = (Image) bufferedImage.getScaledInstance(60, 16, Image.SCALE_SMOOTH);
    
        JLabel ratingLabel = new JLabel(new ImageIcon(scaledImage));
        add(ratingLabel);
                
        JLabel priceLabel = new JLabel();
        priceLabel.setText(price+"TK");
        this.add(priceLabel); 
    }
    
    
    void getRating()
    {
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
